services:

  payment-processor-1:
    image: zanfranceschi/payment-processor
    networks:
      - payment-processor
    hostname: payment-processor-default
    ports:
      - 8001:8080
    # etc...

  payment-processor-2:
    image: zanfranceschi/payment-processor
    networks:
      - payment-processor
    hostname: payment-processor-fallback
    ports:
      - 8002:8080

  api:
    build: .
    ports:
    - "9999:9999"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: rinha
      SPRING_DATASOURCE_PASSWORD: rinha
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    networks:
      - backend
      - payment-processor
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  load-balancer:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./src/main/resources/nginx/nginx.conf:/etc/nginx/nginx.conf  
    - ./src/main/resources/nginx/sites-enabled:/etc/nginx/sites-enabled
    networks:
    - backend
    depends_on:
    - api

  rabbitmq:
    image: rabbitmq:4.1.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

volumes:
  db_data:

networks:

  payment-processor:
    name: payment-processor
    driver: bridge
  
  backend:
    name: backend
    driver: bridge